// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
)

type Expense struct {
	TripID       string
	Date         sql.NullTime
	Description  sql.NullString
	Amount       sql.NullFloat64
	PaidByUserID sql.NullString
	Participants []byte
}

type Schedule struct {
	TripID string
	UserID string
	Date   sql.NullTime
}

type Trip struct {
	TripID    string
	Name      sql.NullString
	StartDate sql.NullTime
	EndDate   sql.NullTime
}

type User struct {
	UserID string
	TripID string
	Name   sql.NullString
}
