// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Expense struct {
	Tripid       sql.NullString
	Date         sql.NullTime
	Description  sql.NullString
	Amount       sql.NullFloat64
	Paidbyuserid sql.NullString
	Participants []byte
}

type Schedule struct {
	Tripid sql.NullString
	Userid sql.NullString
	Date   sql.NullTime
}

type Trip struct {
	Tripid    string
	Name      sql.NullString
	Startdate sql.NullTime
	Enddate   sql.NullTime
}

type User struct {
	Userid string
	Tripid sql.NullString
	Name   sql.NullString
}
